# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitSent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sentiment',
        ),
    ]
