# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitSent', '0003_auto_20160818_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
