# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitSent', '0005_auto_20160819_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
    ]
