# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitSent', '0006_auto_20160819_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
