# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-20 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitSent', '0008_auto_20160819_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetContent', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
